title: Aaron Weisenburger
logo: ![image alt](https://raw.githubuser.com/aaaronweisenburger/aaronweisenburger.github.io/34bd040e5674d2af8b6268c86efae0a21989c466/139594087.jpeg)
description: Sophomore Aerospace Engineering Student @ RPI
show downloads: false
theme: jekyll-theme-minimal
