title: Aaron Weisenburger
logo: https://raw.githubusercontent.com/aaaronweisenburger/aaronweisenburger.github.io/433c9f2162ed3b078343029f98692cb8bbc3233f/139594087.jpeg
#description: Sophomore Aerospace Engineering Student @ RPI
#show downloads: false
theme: jekyll-theme-minimal
