title: Aaron Weisenburger
logo: ![image alt](https://github.com/aaaronweisenburger/aaronweisenburger.github.io/blob/433c9f2162ed3b078343029f98692cb8bbc3233f/139594087.jpeg)
description: Sophomore Aerospace Engineering Student @ RPI
show downloads: false
theme: jekyll-theme-minimal
